theme: jekyll-theme-architect
title: Restaurant Recommendation System Introduction
description: 
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
